version: "3"

services:
  frontend:
    build:
      context: ./letterman-front
      args:
        API_URL: "*"
    container_name: frontend
    volumes:
      - ./letterman-front:/frontend
      - build_folder:/frontend/build
      - ./letterman-front/node_modules/:/frontend/node_modules 
    restart: always
    stdin_open: true 
    tty: true
    networks:
      - doh


  backend:
    container_name: backend
    build: ./backend
    command: >
      bash -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               gunicorn backend.wsgi --bind 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - doh

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:8080
    volumes:
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - doh


  ai:
    container_name: ai
    build: ./ai
    command: >
      bash -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py runserver 0.0.0.0:8081"
    ports:
      - "8081:8081"
    volumes:
      - ./ai:/ai
    depends_on:
      - backend
    networks:
      - doh

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - doh

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    expose:
      - "15672"
    networks:
      - doh
    
  celery_worker_1:
    container_name: celery_worker_1
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh

  celery_worker_2:
    container_name: celery_worker_2
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - doh


  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3100:3000
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=0707
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    expose:
      - 3100
    networks:
      - doh


networks:
  doh:
    driver: bridge

volumes:
  static_volume: null
  media_volume: null
  build_folder: null
  prometheus_data: null
  grafana_data: null