version: "3"

networks:
  doh:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/dist
      - ./frontend/node_modules/:/frontend/node_modules
    tty: true

  backend:
    container_name: backend
    build: ./backend
    command: >
      bash -c "python3 manage.py makemigrations images &&
               python3 manage.py makemigrations styles && 
               python3 manage.py migrate &&
               gunicorn backend.wsgi --bind 0.0.0.0:8080 --timeout 240"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    depends_on:
      - rabbitmq
      - redis
    networks:
      - doh

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
#      - "443:443"
    expose:
      - 80
#      - 443
    volumes:
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - doh

  ai:
    container_name: ai
    build: ./ai
    command: >
      bash -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py runserver 0.0.0.0:8081"
    ports:
      - "8081:8081"
    volumes:
      - ./ai:/ai
    depends_on:
      - backend
    networks:
      - doh

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - doh

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    expose:
      - "15672"
    networks:
      - doh
    
  celery_worker_1:
    container_name: celery_worker_1
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh

  celery_worker_2:
    container_name: celery_worker_2
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh


volumes:
  static_volume: null
  media_volume: null
  build_folder: null
  prometheus_data: null
  grafana_data: null
