global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - send_resolved: true